### ISSUE TITLE
Ta Review Auth

### ISSUE THREAD

**Issue by cjlew** [cjlew/Tempo#20]

**Comment by mfeniseycopes** [comment]
### Styling
- [ ] Remove default link styling (purple when visited)
- [ ] Remove outline and default border stylings on input
- [ ] Add padding on inputs to give a little space before the cursor
- [ ] Styling looks good, but lets get closer to looking exactly like Spotify (colors, fonts, borders, etc)

### Seeds
- Good for now :)

### Bug-free navigation
- [ ] I should not be able to see the login/signup pages if I am already signed in (protect those routes)

**Comment by mfeniseycopes** [comment]
A few more styling nitpickings:

- [ ] Make login/signup inputs `border-style: solid`
- [ ] Increase input text font size
- [ ] Buttons should use all caps
